### ISSUE TITLE
Crash on Entering Aether

### ISSUE THREAD

**Issue by VoidLeech** [null2264/LibreExpFix#5]
### Observed Behaviour
When stepping through an Aether portal, from either the overworld or the Aether, the player crashes.

### Reproduction steps
1. Build Aether Portal (Glowstone + Water)
2. Step through
3. Crash

### Expected Behaviour
No crash happens

### Logs
https://mclo.gs/dbC0WCl

### Other Mods
Aether 1.20.1-1.0.0

**Comment by null2264** [comment]
From the logs, it seems like you're trying to use LibreExpFix for 1.20.2 on MC1.20.1

Can you confirm that you're using the correct LibreExpFix? for 1.20.1 you should get LibreExpFix v0.2.2 for MC 1.18+ (https://modrinth.com/mod/libre-exp-fix/version/0.2.2b9-BETA-forge)

**Comment by VoidLeech** [comment]
I've installed via Prism where it's only presenting me the three MC1.18+ versions to install and I've confirmed via the mods.toml that I should have the 1.20.1 version of v0.2.2: https://mclo.gs/kJjEZd5

**Comment by VoidLeech** [comment]
I did confirm the mod working when travelling to the Otherside (Deeper & Darker) and Undergarden (The Undergarden) before making a crash report (as I was making a pack containing these: they worked) but the initial crash report was without them. I skipped out on the Nether and End. Those actually crash similarly to the Aether.
https://mclo.gs/7qPmp3G (Nether)
https://mclo.gs/FOWcWxS (End)

I've quickly checked whether it was just on Aether's end but the Nether still crashes without Aether (or any other mods for that matter) installed.
https://mclo.gs/QtEmIGB

**Comment by null2264** [comment]
Yeah I found out what happened, it's forge being forge, not sure how to fix it at the moment so it may take awhile...

**Comment by null2264** [comment]
Should be fixed in [v0.2.3](https://modrinth.com/mod/libre-exp-fix/version/0.2.3+1.18b10-BETA-forge).

**Comment by VoidLeech** [comment]
I unfortunately still crash. NoSuchMethodError again, different obfuscated method. I believe it's now failing on the player.getId() call.
https://mclo.gs/BtzxFjG
Could this be a sidedness issue or is it more of the same forge being forge? As I understand it a singleplayer world still uses an internal server but I could be mistaken. Or if singleplayer is never the intended use case of the mod you can close this issue and I'll try again when I do get a dedicated server.

**Comment by null2264** [comment]
It's both singleplayer (integrated) and dedicated... it's just caused by how Forge handle mods compared to Fabric, it rely too heavily on MC version... I'll try to fix it later today, probably need to rethink a different approach for Forge specifically.

**Comment by null2264** [comment]
Try this build: https://cdn.aap.my.id/libreexpfix-0.2.3+1.18b77-BETA-forge.jar
It works on my end, so hopefully that finally fix it frfr...

**Comment by VoidLeech** [comment]
Yes, that seems to work in all cases that it crashed earlier. Thank you for your effort!

**Comment by null2264** [comment]
Fixed in v0.2.4
